[package]
name = "smartauto-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.15.2"
prost = "0.13.4"
scylla = "0.15.1"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"
tonic-types = "0.12.3"
tonic-web = "0.12.3"
tower = "0.5.2"
tower-http = {version = "0.6.2", features = ["cors"]}

[build-dependencies]
tonic-build = "0.12.3"
