[config]
default_to_workspace = false

[tasks.run]
dependencies = [
    "format",
    "build",
    "run-only"
]

[tasks.run-only]
cwd = "core"
command = "trunk"
args = ["serve"]

[tasks.test]
command = "echo"
args = ["skipped"]
