# This is primary for precommit
[workspace]
resolver = "2"
members = [
    "backend/core",
    "backend/plugins/*",
    "frontend/core",
    "frontend/plugins/*",
]
# Prevent nested workspace errors
exclude = ["backend", "frontend"]
