cargo-features = ["codegen-backend"]

[workspace]
resolver = "2"
members = ["backend/core", "backend/plugins/*"]

[workspace.metadata.cargo-machete]
ignored = ["prost"]

[profile.dev]
codegen-backend = "cranelift"
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
