[unstable]
codegen-backend = true

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[build]
rustflags = ["-Z", "threads=8"]

[profile.server-dev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
