name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly && rustup component add rustfmt && rustup component add clippy
      - uses: actions/setup-python@v5
      - uses: arduino/setup-protoc@v3
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: python -m pip install pre-commit
      - name: Install dependencies
        run: bun install --no-save
      - name: install protobuf-es
        run: bun add -g @bufbuild/protoc-gen-es
      - uses: pre-commit/action@v3.0.1
