name: pre-commit
on:
  pull_request:
  push:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rui314/setup-mold@v1
      - run: cargo fetch
      - name: Install cranelift
        run: rustup component add rustc-codegen-cranelift-preview --toolchain nightly
      - uses: actions/setup-python@v5
      - uses: arduino/setup-protoc@v3
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: python -m pip install pre-commit
